'use strict';

const CANARY_SOURCE_SNAPSHOT_PROVIDER_VERSION =
  'canary-source-snapshot-provider.v1';
const CANARY_SOURCE_TREE_SCHEMA_VERSION = 'canary-source-tree.v1';
const CANARY_SOURCE_USER_STATE_SCHEMA_VERSION = 'canary-source-user-state.v1';
const CANARY_SOURCE_BRANCH_STATE_SCHEMA_VERSION = 'canary-source-branch-state.v1';
const CANARY_SOURCE_INDEX_STATE_SCHEMA_VERSION = 'canary-source-index-state.v1';
const CANARY_SOURCE_CHECKPOINT_SCHEMA_VERSION = 'canary-source-checkpoint.v1';

const CANARY_SOURCE_SNAPSHOT_PROVIDER_DIAGNOSTICS = Object.freeze({
  version: CANARY_SOURCE_SNAPSHOT_PROVIDER_VERSION,
  rootReadMode: 'pinned_authority_reader',
  checkpointMode: 'verified',
  mutationObservation: 'exclusive_job',
});

module.exports = {
  CANARY_SOURCE_BRANCH_STATE_SCHEMA_VERSION,
  CANARY_SOURCE_CHECKPOINT_SCHEMA_VERSION,
  CANARY_SOURCE_INDEX_STATE_SCHEMA_VERSION,
  CANARY_SOURCE_SNAPSHOT_PROVIDER_DIAGNOSTICS,
  CANARY_SOURCE_SNAPSHOT_PROVIDER_VERSION,
  CANARY_SOURCE_TREE_SCHEMA_VERSION,
  CANARY_SOURCE_USER_STATE_SCHEMA_VERSION,
};
