'use strict';

const CANARY_PROMOTION_ROLLBACK_STORE_VERSION =
  'canary-promotion-rollback-store.v1';
const CANARY_PROMOTION_ROLLBACK_STORE_SNAPSHOT_SCHEMA_VERSION =
  'canary-promotion-rollback-store-snapshot.v1';
const CANARY_PROMOTION_ROLLBACK_PREPARED_SCHEMA_VERSION =
  'canary-promotion-rollback-prepared.v1';
const CANARY_PROMOTION_ROLLBACK_COMMIT_SCHEMA_VERSION =
  'canary-promotion-rollback-commit.v1';
const CANARY_PROMOTION_ROLLBACK_RECOVERY_SCHEMA_VERSION =
  'canary-promotion-rollback-recovery.v1';
const CANARY_PROMOTION_ROLLBACK_CANCEL_SCHEMA_VERSION =
  'canary-promotion-rollback-cancel.v1';
const CANARY_PROMOTION_ROLLBACK_SETTLEMENT_SCHEMA_VERSION =
  'canary-promotion-rollback-settlement.v1';

module.exports = {
  CANARY_PROMOTION_ROLLBACK_CANCEL_SCHEMA_VERSION,
  CANARY_PROMOTION_ROLLBACK_COMMIT_SCHEMA_VERSION,
  CANARY_PROMOTION_ROLLBACK_PREPARED_SCHEMA_VERSION,
  CANARY_PROMOTION_ROLLBACK_RECOVERY_SCHEMA_VERSION,
  CANARY_PROMOTION_ROLLBACK_SETTLEMENT_SCHEMA_VERSION,
  CANARY_PROMOTION_ROLLBACK_STORE_SNAPSHOT_SCHEMA_VERSION,
  CANARY_PROMOTION_ROLLBACK_STORE_VERSION,
};
