(function () {
  function getAiSettingsElements() {
    const queryAll = (selector) => {
      if (!document.querySelectorAll) return [];
      return Array.from(document.querySelectorAll(selector));
    };
    return {
          composerProvider: document.getElementById('composer-provider'),
          modal: document.getElementById('ai-settings-modal'),
          backdrop: document.getElementById('ai-settings-backdrop'),
          close: document.getElementById('ai-settings-close'),
          cancel: document.getElementById('ai-settings-cancel'),
          save: document.getElementById('ai-settings-save'),
          current: document.getElementById('ai-settings-current'),
          homePanel: document.getElementById('ai-settings-home-panel'),
          languagePanel: document.getElementById('ai-settings-language-panel'),
          appearancePanel: document.getElementById('ai-settings-appearance-panel'),
          workspacePanel: document.getElementById('ai-settings-workspace-panel'),
          accountPanel: document.getElementById('ai-settings-account-panel'),
          apisPanel: document.getElementById('ai-settings-apis-panel'),
          mcpPanel: document.getElementById('ai-settings-mcp-panel'),
          openLanguage: document.getElementById('ai-settings-open-language'),
          openAppearance: document.getElementById('ai-settings-open-appearance'),
          openWorkspace: document.getElementById('ai-settings-open-workspace'),
          openAccount: document.getElementById('ai-settings-open-account'),
          openApis: document.getElementById('ai-settings-open-apis'),
          openMcp: document.getElementById('ai-settings-open-mcp'),
          language: document.getElementById('ai-settings-language'),
          theme: document.getElementById('ai-settings-theme'),
          fontScale: document.getElementById('ai-settings-font-scale'),
          fontScaleValue: document.getElementById('ai-settings-font-scale-value'),
          workspaceMode: document.getElementById('ai-settings-workspace-mode'),
          workspaceLeftCollapsed: document.getElementById('ai-settings-left-collapsed'),
          workspaceRightCollapsed: document.getElementById('ai-settings-right-collapsed'),
          workspaceLeftSlot: document.getElementById('ai-settings-left-slot'),
          workspaceRightSlot: document.getElementById('ai-settings-right-slot'),
          workspaceTerminalDock: document.getElementById('ai-settings-terminal-dock'),
          workspacePresetButtons: queryAll('[data-workspace-preset]'),
          workspaceToolChips: queryAll('[data-workspace-tool]'),
          workspaceDropZones: queryAll('[data-workspace-zone]'),
          workspaceZoneItemContainers: queryAll('[data-workspace-zone-items]'),
          backHome: document.getElementById('ai-settings-back-home'),
          backHomeAppearance: document.getElementById('ai-settings-back-home-appearance'),
          backHomeWorkspace: document.getElementById('ai-settings-back-home-workspace'),
          backHomeAccount: document.getElementById('ai-settings-back-home-account'),
          backHomeApis: document.getElementById('ai-settings-back-home-apis'),
          backHomeMcp: document.getElementById('ai-settings-back-home-mcp'),
          accountStatus: document.getElementById('ai-settings-account-status'),
          accountGoogleLogin: document.getElementById('ai-settings-google-login'),
          accountSignOut: document.getElementById('ai-settings-sign-out'),
          accountEmail: document.getElementById('ai-settings-account-email'),
          accountEmailStart: document.getElementById('ai-settings-email-start'),
          accountCode: document.getElementById('ai-settings-account-code'),
          accountEmailComplete: document.getElementById('ai-settings-email-complete'),
          apiList: document.getElementById('ai-settings-api-list'),
          addProvider: document.getElementById('ai-settings-add-provider'),
          addApi: document.getElementById('ai-settings-add-api'),
          editor: document.getElementById('ai-settings-api-editor'),
          editorId: document.getElementById('ai-settings-editor-id'),
          editorKind: document.getElementById('ai-settings-editor-kind'),
          editorProvider: document.getElementById('ai-settings-editor-provider'),
          editorLabel: document.getElementById('ai-settings-editor-label'),
          editorModelPreset: document.getElementById('ai-settings-editor-model-preset'),
          editorModel: document.getElementById('ai-settings-editor-model'),
          editorKey: document.getElementById('ai-settings-editor-key'),
          editorWebsite: document.getElementById('ai-settings-editor-website'),
          editorCancel: document.getElementById('ai-settings-editor-cancel'),
          editorSave: document.getElementById('ai-settings-editor-save'),
          providerHelp: document.getElementById('ai-settings-provider-help'),
          providerHelpLink: document.getElementById('ai-settings-provider-help-link'),
          mcpStatus: document.getElementById('ai-settings-mcp-status'),
          mcpPresetSelect: document.getElementById('ai-settings-mcp-preset-select'),
          mcpPresetApply: document.getElementById('ai-settings-mcp-preset-apply'),
          mcpList: document.getElementById('ai-settings-mcp-list'),
          mcpId: document.getElementById('ai-settings-mcp-id'),
          mcpName: document.getElementById('ai-settings-mcp-name'),
          mcpTransport: document.getElementById('ai-settings-mcp-transport'),
          mcpCommand: document.getElementById('ai-settings-mcp-command'),
          mcpEndpoint: document.getElementById('ai-settings-mcp-endpoint'),
          mcpTimeout: document.getElementById('ai-settings-mcp-timeout'),
          mcpAllowed: document.getElementById('ai-settings-mcp-allowed'),
          mcpBlocked: document.getElementById('ai-settings-mcp-blocked'),
          mcpPermissions: document.getElementById('ai-settings-mcp-permissions'),
          mcpBlockedRisks: document.getElementById('ai-settings-mcp-blocked-risks'),
          mcpMaxRisk: document.getElementById('ai-settings-mcp-max-risk'),
          mcpAllowedDirectories: document.getElementById('ai-settings-mcp-allowed-directories'),
          mcpBlockedDirectories: document.getElementById('ai-settings-mcp-blocked-directories'),
          mcpAllowedNetworkHosts: document.getElementById('ai-settings-mcp-allowed-network-hosts'),
          mcpBlockedNetworkHosts: document.getElementById('ai-settings-mcp-blocked-network-hosts'),
          mcpEnv: document.getElementById('ai-settings-mcp-env'),
          mcpHeaders: document.getElementById('ai-settings-mcp-headers'),
          mcpEnabled: document.getElementById('ai-settings-mcp-enabled'),
          mcpApproved: document.getElementById('ai-settings-mcp-approved'),
          mcpHighRiskAllow: document.getElementById('ai-settings-mcp-high-risk-allow'),
          mcpInjectSession: document.getElementById('ai-settings-mcp-inject-session'),
          mcpAllowExternalNetwork: document.getElementById('ai-settings-mcp-allow-external-network'),
          mcpNew: document.getElementById('ai-settings-mcp-new'),
          mcpSave: document.getElementById('ai-settings-mcp-save'),
        };
  }

  window.FaberAiSettingsElements = {
    getAiSettingsElements,
  };
})();
