(function () {
  function getAiSettingsElements() {
    return {
          composerProvider: document.getElementById('composer-provider'),
          modal: document.getElementById('ai-settings-modal'),
          backdrop: document.getElementById('ai-settings-backdrop'),
          close: document.getElementById('ai-settings-close'),
          cancel: document.getElementById('ai-settings-cancel'),
          save: document.getElementById('ai-settings-save'),
          current: document.getElementById('ai-settings-current'),
          homePanel: document.getElementById('ai-settings-home-panel'),
          languagePanel: document.getElementById('ai-settings-language-panel'),
          appearancePanel: document.getElementById('ai-settings-appearance-panel'),
          accountPanel: document.getElementById('ai-settings-account-panel'),
          apisPanel: document.getElementById('ai-settings-apis-panel'),
          openLanguage: document.getElementById('ai-settings-open-language'),
          openAppearance: document.getElementById('ai-settings-open-appearance'),
          openAccount: document.getElementById('ai-settings-open-account'),
          openApis: document.getElementById('ai-settings-open-apis'),
          language: document.getElementById('ai-settings-language'),
          theme: document.getElementById('ai-settings-theme'),
          fontScale: document.getElementById('ai-settings-font-scale'),
          fontScaleValue: document.getElementById('ai-settings-font-scale-value'),
          backHome: document.getElementById('ai-settings-back-home'),
          backHomeAppearance: document.getElementById('ai-settings-back-home-appearance'),
          backHomeAccount: document.getElementById('ai-settings-back-home-account'),
          backHomeApis: document.getElementById('ai-settings-back-home-apis'),
          accountStatus: document.getElementById('ai-settings-account-status'),
          accountGoogleLogin: document.getElementById('ai-settings-google-login'),
          accountSignOut: document.getElementById('ai-settings-sign-out'),
          accountEmail: document.getElementById('ai-settings-account-email'),
          accountEmailStart: document.getElementById('ai-settings-email-start'),
          accountCode: document.getElementById('ai-settings-account-code'),
          accountEmailComplete: document.getElementById('ai-settings-email-complete'),
          apiList: document.getElementById('ai-settings-api-list'),
          addProvider: document.getElementById('ai-settings-add-provider'),
          addApi: document.getElementById('ai-settings-add-api'),
          editor: document.getElementById('ai-settings-api-editor'),
          editorId: document.getElementById('ai-settings-editor-id'),
          editorKind: document.getElementById('ai-settings-editor-kind'),
          editorProvider: document.getElementById('ai-settings-editor-provider'),
          editorLabel: document.getElementById('ai-settings-editor-label'),
          editorModelPreset: document.getElementById('ai-settings-editor-model-preset'),
          editorModel: document.getElementById('ai-settings-editor-model'),
          editorKey: document.getElementById('ai-settings-editor-key'),
          editorWebsite: document.getElementById('ai-settings-editor-website'),
          editorCancel: document.getElementById('ai-settings-editor-cancel'),
          editorSave: document.getElementById('ai-settings-editor-save'),
          providerHelp: document.getElementById('ai-settings-provider-help'),
          providerHelpLink: document.getElementById('ai-settings-provider-help-link'),
        };
  }

  window.FaberAiSettingsElements = {
    getAiSettingsElements,
  };
})();
